name       : haskell-structured
version    : 0.1
release    : 1
source     :
    - https://hackage.haskell.org/package/structured-0.1/structured-0.1.tar.gz : 9c636798adba8ada22566f2dd6f979ec814fe12eb409cb9e447f65dee5a9a076
license    : BSD-3-Clause
component  : programming.haskell
summary    : Structure (hash) of your data types
description: |
    Calculate the hash of a data structure. It can be used as a magic number for the serialization formats.
builddeps  :
    - haskell-aeson-devel
    - haskell-base16-bytestring-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-aeson-devel
        - haskell-base16-bytestring-devel
networking : yes
setup      : |
    sed -i "s|<1.5|<1.6|g" structured.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
